name: Trigger CircleCI workflow

on:
  pull_request:
    types: [labeled]

jobs:
  trigger:
    if: github.event.label.name == 'run all e2e tests'
    name: Run workflow with all e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Compute branch data
        run: |
          export IS_PR_FROM_FORK=${{github.event.pull_request.head.repo.fork}}
          echo $IS_PR_FROM_FORK
      - name: Do things
        run: |
          echo "${{github.event.pull_request.head.repo.fork}}"
          echo $IS_PR_FROM_FORK
      - name: Make request to CircleCI (for non-forked-base PR)
        run: >
          curl --request POST
          --url https://circleci.com/api/v2/project/gh/storybookjs/storybook/pipeline
          --header 'Circle-Token: '"$CIRCLE_CI_TOKEN"' '
          --header 'content-type: application/json'
          --data '{"branch":"${{ github.event.pull_request.head.ref }}"}'
        env:
          CIRCLE_CI_TOKEN: ${{ secrets.CIRCLE_CI_TOKEN_GMAISSE_TEST }}
